apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app-container
          image: jorgelmp/colegio-cdmx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: phpapp-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
  selector:
    app: php-app
