apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servidor-web
  template:
    metadata:
      labels:
        app: servidor-web
    spec:
      containers:
        - name: nginx
          image: jorgelmp/colegio-cdmx:latest
          ports:
            - containerPort: 80