apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servidor-web
  template:
    metadata:
      labels:
        app: servidor-web
    spec:
      containers:
        - name: colegio-cdmx-httpd
          image: jorgelmp/colegio-cdmx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servidor-web-service
spec:
  selector:
    app: servidor-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort